name: Rebuild after changes

on:
  push:
    branches: [ "main" ]

jobs:
  pylint:
    uses: ./.github/workflows/pylint.yml
  build_push:
    needs: pylint
    uses: ./.github/workflows/build_push.yml
    secrets: 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  pull_and_run:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - 
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_app:latest
          docker run -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/my_app:latest
